package com.kinzr.apellian.entity.staging;

public class CdWeddingHall {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WEDDING_HALL.ID_WEDDING_HALL
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    private Integer idWeddingHall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WEDDING_HALL.NM_WEDDING_HALL
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    private String nmWeddingHall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WEDDING_HALL.DS_ADDR
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    private String dsAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WEDDING_HALL.ID_WEDDING_HALL
     *
     * @return the value of CD_WEDDING_HALL.ID_WEDDING_HALL
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    public Integer getIdWeddingHall() {
        return idWeddingHall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WEDDING_HALL.ID_WEDDING_HALL
     *
     * @param idWeddingHall the value for CD_WEDDING_HALL.ID_WEDDING_HALL
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    public void setIdWeddingHall(Integer idWeddingHall) {
        this.idWeddingHall = idWeddingHall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WEDDING_HALL.NM_WEDDING_HALL
     *
     * @return the value of CD_WEDDING_HALL.NM_WEDDING_HALL
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    public String getNmWeddingHall() {
        return nmWeddingHall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WEDDING_HALL.NM_WEDDING_HALL
     *
     * @param nmWeddingHall the value for CD_WEDDING_HALL.NM_WEDDING_HALL
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    public void setNmWeddingHall(String nmWeddingHall) {
        this.nmWeddingHall = nmWeddingHall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WEDDING_HALL.DS_ADDR
     *
     * @return the value of CD_WEDDING_HALL.DS_ADDR
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    public String getDsAddr() {
        return dsAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WEDDING_HALL.DS_ADDR
     *
     * @param dsAddr the value for CD_WEDDING_HALL.DS_ADDR
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    public void setDsAddr(String dsAddr) {
        this.dsAddr = dsAddr;
    }
}