package com.kinzr.apellian.entity.staging;

import com.kinzr.apellian.entity.staging.CdWeddingHall;
import java.util.List;

public interface CdWeddingHallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WEDDING_HALL
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    int deleteByPrimaryKey(Integer idWeddingHall);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WEDDING_HALL
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    int insert(CdWeddingHall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WEDDING_HALL
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    CdWeddingHall selectByPrimaryKey(Integer idWeddingHall);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WEDDING_HALL
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    List<CdWeddingHall> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WEDDING_HALL
     *
     * @mbg.generated Fri May 08 15:13:12 KST 2020
     */
    int updateByPrimaryKey(CdWeddingHall record);
}