package com.kinzr.apellian.entity.model;

import java.util.Date;

public class AuthCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_CODE.ID_AUTH_CODE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Long idAuthCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_CODE.CD_AUTH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String cdAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_CODE.TY_AUTH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String tyAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_CODE.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Date dtReg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_CODE.ID_AUTH_CODE
     *
     * @return the value of AUTH_CODE.ID_AUTH_CODE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Long getIdAuthCode() {
        return idAuthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_CODE.ID_AUTH_CODE
     *
     * @param idAuthCode the value for AUTH_CODE.ID_AUTH_CODE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdAuthCode(Long idAuthCode) {
        this.idAuthCode = idAuthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_CODE.CD_AUTH
     *
     * @return the value of AUTH_CODE.CD_AUTH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getCdAuth() {
        return cdAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_CODE.CD_AUTH
     *
     * @param cdAuth the value for AUTH_CODE.CD_AUTH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdAuth(String cdAuth) {
        this.cdAuth = cdAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_CODE.TY_AUTH
     *
     * @return the value of AUTH_CODE.TY_AUTH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getTyAuth() {
        return tyAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_CODE.TY_AUTH
     *
     * @param tyAuth the value for AUTH_CODE.TY_AUTH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setTyAuth(String tyAuth) {
        this.tyAuth = tyAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_CODE.DT_REG
     *
     * @return the value of AUTH_CODE.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Date getDtReg() {
        return dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_CODE.DT_REG
     *
     * @param dtReg the value for AUTH_CODE.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDtReg(Date dtReg) {
        this.dtReg = dtReg;
    }
}