package com.kinzr.apellian.entity.model;

public class BnfClassBnfImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_CLASS_BNF_IMAGES.ID_BNF_CLASS_BNF_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idBnfClassBnfImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_CLASS_BNF_IMAGES.ID_BNF_CLASS
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idBnfClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_CLASS_BNF_IMAGES.NM_BNF_CLASS_BNF_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String nmBnfClassBnfImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_CLASS_BNF_IMAGES.URL_BNF_CLASS_BNF_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String urlBnfClassBnfImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_CLASS_BNF_IMAGES.ID_BNF_CLASS_BNF_IMAGE
     *
     * @return the value of BNF_CLASS_BNF_IMAGES.ID_BNF_CLASS_BNF_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdBnfClassBnfImage() {
        return idBnfClassBnfImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_CLASS_BNF_IMAGES.ID_BNF_CLASS_BNF_IMAGE
     *
     * @param idBnfClassBnfImage the value for BNF_CLASS_BNF_IMAGES.ID_BNF_CLASS_BNF_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdBnfClassBnfImage(Integer idBnfClassBnfImage) {
        this.idBnfClassBnfImage = idBnfClassBnfImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_CLASS_BNF_IMAGES.ID_BNF_CLASS
     *
     * @return the value of BNF_CLASS_BNF_IMAGES.ID_BNF_CLASS
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdBnfClass() {
        return idBnfClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_CLASS_BNF_IMAGES.ID_BNF_CLASS
     *
     * @param idBnfClass the value for BNF_CLASS_BNF_IMAGES.ID_BNF_CLASS
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdBnfClass(Integer idBnfClass) {
        this.idBnfClass = idBnfClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_CLASS_BNF_IMAGES.NM_BNF_CLASS_BNF_IMAGE
     *
     * @return the value of BNF_CLASS_BNF_IMAGES.NM_BNF_CLASS_BNF_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getNmBnfClassBnfImage() {
        return nmBnfClassBnfImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_CLASS_BNF_IMAGES.NM_BNF_CLASS_BNF_IMAGE
     *
     * @param nmBnfClassBnfImage the value for BNF_CLASS_BNF_IMAGES.NM_BNF_CLASS_BNF_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNmBnfClassBnfImage(String nmBnfClassBnfImage) {
        this.nmBnfClassBnfImage = nmBnfClassBnfImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_CLASS_BNF_IMAGES.URL_BNF_CLASS_BNF_IMAGE
     *
     * @return the value of BNF_CLASS_BNF_IMAGES.URL_BNF_CLASS_BNF_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getUrlBnfClassBnfImage() {
        return urlBnfClassBnfImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_CLASS_BNF_IMAGES.URL_BNF_CLASS_BNF_IMAGE
     *
     * @param urlBnfClassBnfImage the value for BNF_CLASS_BNF_IMAGES.URL_BNF_CLASS_BNF_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setUrlBnfClassBnfImage(String urlBnfClassBnfImage) {
        this.urlBnfClassBnfImage = urlBnfClassBnfImage;
    }
}