package com.kinzr.apellian.entity.model;

public class BnfClassImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_CLASS_IMAGES.ID_BNF_CLASS_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idBnfClassImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_CLASS_IMAGES.ID_BNF_CLASS
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idBnfClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_CLASS_IMAGES.NM_BNF_CLASS_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String nmBnfClassImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_CLASS_IMAGES.URL_BNF_CLASS_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String urlBnfClassImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_CLASS_IMAGES.ID_BNF_CLASS_IMAGE
     *
     * @return the value of BNF_CLASS_IMAGES.ID_BNF_CLASS_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdBnfClassImage() {
        return idBnfClassImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_CLASS_IMAGES.ID_BNF_CLASS_IMAGE
     *
     * @param idBnfClassImage the value for BNF_CLASS_IMAGES.ID_BNF_CLASS_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdBnfClassImage(Integer idBnfClassImage) {
        this.idBnfClassImage = idBnfClassImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_CLASS_IMAGES.ID_BNF_CLASS
     *
     * @return the value of BNF_CLASS_IMAGES.ID_BNF_CLASS
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdBnfClass() {
        return idBnfClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_CLASS_IMAGES.ID_BNF_CLASS
     *
     * @param idBnfClass the value for BNF_CLASS_IMAGES.ID_BNF_CLASS
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdBnfClass(Integer idBnfClass) {
        this.idBnfClass = idBnfClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_CLASS_IMAGES.NM_BNF_CLASS_IMAGE
     *
     * @return the value of BNF_CLASS_IMAGES.NM_BNF_CLASS_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getNmBnfClassImage() {
        return nmBnfClassImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_CLASS_IMAGES.NM_BNF_CLASS_IMAGE
     *
     * @param nmBnfClassImage the value for BNF_CLASS_IMAGES.NM_BNF_CLASS_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNmBnfClassImage(String nmBnfClassImage) {
        this.nmBnfClassImage = nmBnfClassImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_CLASS_IMAGES.URL_BNF_CLASS_IMAGE
     *
     * @return the value of BNF_CLASS_IMAGES.URL_BNF_CLASS_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getUrlBnfClassImage() {
        return urlBnfClassImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_CLASS_IMAGES.URL_BNF_CLASS_IMAGE
     *
     * @param urlBnfClassImage the value for BNF_CLASS_IMAGES.URL_BNF_CLASS_IMAGE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setUrlBnfClassImage(String urlBnfClassImage) {
        this.urlBnfClassImage = urlBnfClassImage;
    }
}