package com.kinzr.apellian.entity.model;

import java.util.Date;

public class BnfEventApplication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_APPLICATION.ID_EVENT_APPLICATION
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private Integer idEventApplication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_APPLICATION.ID_BNF_EVENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private Integer idBnfEvent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_APPLICATION.ID_USER
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private String idUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_APPLICATION.DS_PARTNER
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private String dsPartner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_APPLICATION.NM_APPLY
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private String nmApply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_APPLICATION.TEL_APPLY
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private String telApply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_APPLICATION.CD_WIN
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private String cdWin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_APPLICATION.ID_PAYMENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private Long idPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_APPLICATION.DT_REG
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private Date dtReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_APPLICATION.DS_APPLY
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private String dsApply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_APPLICATION.DS_BRAND
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private String dsBrand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_APPLICATION.ID_EVENT_APPLICATION
     *
     * @return the value of BNF_EVENT_APPLICATION.ID_EVENT_APPLICATION
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public Integer getIdEventApplication() {
        return idEventApplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_APPLICATION.ID_EVENT_APPLICATION
     *
     * @param idEventApplication the value for BNF_EVENT_APPLICATION.ID_EVENT_APPLICATION
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setIdEventApplication(Integer idEventApplication) {
        this.idEventApplication = idEventApplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_APPLICATION.ID_BNF_EVENT
     *
     * @return the value of BNF_EVENT_APPLICATION.ID_BNF_EVENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public Integer getIdBnfEvent() {
        return idBnfEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_APPLICATION.ID_BNF_EVENT
     *
     * @param idBnfEvent the value for BNF_EVENT_APPLICATION.ID_BNF_EVENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setIdBnfEvent(Integer idBnfEvent) {
        this.idBnfEvent = idBnfEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_APPLICATION.ID_USER
     *
     * @return the value of BNF_EVENT_APPLICATION.ID_USER
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public String getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_APPLICATION.ID_USER
     *
     * @param idUser the value for BNF_EVENT_APPLICATION.ID_USER
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_APPLICATION.DS_PARTNER
     *
     * @return the value of BNF_EVENT_APPLICATION.DS_PARTNER
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public String getDsPartner() {
        return dsPartner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_APPLICATION.DS_PARTNER
     *
     * @param dsPartner the value for BNF_EVENT_APPLICATION.DS_PARTNER
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setDsPartner(String dsPartner) {
        this.dsPartner = dsPartner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_APPLICATION.NM_APPLY
     *
     * @return the value of BNF_EVENT_APPLICATION.NM_APPLY
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public String getNmApply() {
        return nmApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_APPLICATION.NM_APPLY
     *
     * @param nmApply the value for BNF_EVENT_APPLICATION.NM_APPLY
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setNmApply(String nmApply) {
        this.nmApply = nmApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_APPLICATION.TEL_APPLY
     *
     * @return the value of BNF_EVENT_APPLICATION.TEL_APPLY
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public String getTelApply() {
        return telApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_APPLICATION.TEL_APPLY
     *
     * @param telApply the value for BNF_EVENT_APPLICATION.TEL_APPLY
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setTelApply(String telApply) {
        this.telApply = telApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_APPLICATION.CD_WIN
     *
     * @return the value of BNF_EVENT_APPLICATION.CD_WIN
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public String getCdWin() {
        return cdWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_APPLICATION.CD_WIN
     *
     * @param cdWin the value for BNF_EVENT_APPLICATION.CD_WIN
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setCdWin(String cdWin) {
        this.cdWin = cdWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_APPLICATION.ID_PAYMENT
     *
     * @return the value of BNF_EVENT_APPLICATION.ID_PAYMENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public Long getIdPayment() {
        return idPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_APPLICATION.ID_PAYMENT
     *
     * @param idPayment the value for BNF_EVENT_APPLICATION.ID_PAYMENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setIdPayment(Long idPayment) {
        this.idPayment = idPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_APPLICATION.DT_REG
     *
     * @return the value of BNF_EVENT_APPLICATION.DT_REG
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public Date getDtReg() {
        return dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_APPLICATION.DT_REG
     *
     * @param dtReg the value for BNF_EVENT_APPLICATION.DT_REG
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setDtReg(Date dtReg) {
        this.dtReg = dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_APPLICATION.DS_APPLY
     *
     * @return the value of BNF_EVENT_APPLICATION.DS_APPLY
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public String getDsApply() {
        return dsApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_APPLICATION.DS_APPLY
     *
     * @param dsApply the value for BNF_EVENT_APPLICATION.DS_APPLY
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setDsApply(String dsApply) {
        this.dsApply = dsApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_APPLICATION.DS_BRAND
     *
     * @return the value of BNF_EVENT_APPLICATION.DS_BRAND
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public String getDsBrand() {
        return dsBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_APPLICATION.DS_BRAND
     *
     * @param dsBrand the value for BNF_EVENT_APPLICATION.DS_BRAND
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setDsBrand(String dsBrand) {
        this.dsBrand = dsBrand;
    }
}