package com.kinzr.apellian.entity.model;

import java.math.BigDecimal;
import java.util.Date;

public class BnfEvent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.ID_BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private Integer idBnfEvent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.CD_PROGRESS
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String cdProgress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.NM_BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String nmBnfEvent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsBnfEvent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DT_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private Date dtEvent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.TM_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String tmEvent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.NM_PLACE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String nmPlace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.YN_PRE_COUPLE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String ynPreCouple;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.YN_NEWLY_COUPLE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String ynNewlyCouple;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DT_APPLY_FROM
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private Date dtApplyFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DT_APPLY_TO
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private Date dtApplyTo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_ADDR
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.PT_LAT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private BigDecimal ptLat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.PT_LONG
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private BigDecimal ptLong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_WINNER_NOTICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsWinnerNotice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.AM_PRICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String amPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_PRICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_REFUND
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsRefund;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DT_REG
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private Date dtReg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_PERSONS
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsPersons;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_ABOUT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsAbout;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_FOR
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsFor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_CURRICULUM
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsCurriculum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_BENEFIT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsBenefit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_APPLY
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsApply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_NOTICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsNotice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BNF_EVENT.DS_PARKING
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	private String dsParking;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.ID_BNF_EVENT
	 * @return  the value of BNF_EVENT.ID_BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public Integer getIdBnfEvent() {
		return idBnfEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.ID_BNF_EVENT
	 * @param idBnfEvent  the value for BNF_EVENT.ID_BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setIdBnfEvent(Integer idBnfEvent) {
		this.idBnfEvent = idBnfEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.CD_PROGRESS
	 * @return  the value of BNF_EVENT.CD_PROGRESS
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getCdProgress() {
		return cdProgress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.CD_PROGRESS
	 * @param cdProgress  the value for BNF_EVENT.CD_PROGRESS
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setCdProgress(String cdProgress) {
		this.cdProgress = cdProgress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.NM_BNF_EVENT
	 * @return  the value of BNF_EVENT.NM_BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getNmBnfEvent() {
		return nmBnfEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.NM_BNF_EVENT
	 * @param nmBnfEvent  the value for BNF_EVENT.NM_BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setNmBnfEvent(String nmBnfEvent) {
		this.nmBnfEvent = nmBnfEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_BNF_EVENT
	 * @return  the value of BNF_EVENT.DS_BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsBnfEvent() {
		return dsBnfEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_BNF_EVENT
	 * @param dsBnfEvent  the value for BNF_EVENT.DS_BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsBnfEvent(String dsBnfEvent) {
		this.dsBnfEvent = dsBnfEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DT_EVENT
	 * @return  the value of BNF_EVENT.DT_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public Date getDtEvent() {
		return dtEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DT_EVENT
	 * @param dtEvent  the value for BNF_EVENT.DT_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDtEvent(Date dtEvent) {
		this.dtEvent = dtEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.TM_EVENT
	 * @return  the value of BNF_EVENT.TM_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getTmEvent() {
		return tmEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.TM_EVENT
	 * @param tmEvent  the value for BNF_EVENT.TM_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setTmEvent(String tmEvent) {
		this.tmEvent = tmEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.NM_PLACE
	 * @return  the value of BNF_EVENT.NM_PLACE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getNmPlace() {
		return nmPlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.NM_PLACE
	 * @param nmPlace  the value for BNF_EVENT.NM_PLACE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setNmPlace(String nmPlace) {
		this.nmPlace = nmPlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.YN_PRE_COUPLE
	 * @return  the value of BNF_EVENT.YN_PRE_COUPLE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getYnPreCouple() {
		return ynPreCouple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.YN_PRE_COUPLE
	 * @param ynPreCouple  the value for BNF_EVENT.YN_PRE_COUPLE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setYnPreCouple(String ynPreCouple) {
		this.ynPreCouple = ynPreCouple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.YN_NEWLY_COUPLE
	 * @return  the value of BNF_EVENT.YN_NEWLY_COUPLE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getYnNewlyCouple() {
		return ynNewlyCouple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.YN_NEWLY_COUPLE
	 * @param ynNewlyCouple  the value for BNF_EVENT.YN_NEWLY_COUPLE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setYnNewlyCouple(String ynNewlyCouple) {
		this.ynNewlyCouple = ynNewlyCouple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DT_APPLY_FROM
	 * @return  the value of BNF_EVENT.DT_APPLY_FROM
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public Date getDtApplyFrom() {
		return dtApplyFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DT_APPLY_FROM
	 * @param dtApplyFrom  the value for BNF_EVENT.DT_APPLY_FROM
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDtApplyFrom(Date dtApplyFrom) {
		this.dtApplyFrom = dtApplyFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DT_APPLY_TO
	 * @return  the value of BNF_EVENT.DT_APPLY_TO
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public Date getDtApplyTo() {
		return dtApplyTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DT_APPLY_TO
	 * @param dtApplyTo  the value for BNF_EVENT.DT_APPLY_TO
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDtApplyTo(Date dtApplyTo) {
		this.dtApplyTo = dtApplyTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_ADDR
	 * @return  the value of BNF_EVENT.DS_ADDR
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsAddr() {
		return dsAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_ADDR
	 * @param dsAddr  the value for BNF_EVENT.DS_ADDR
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsAddr(String dsAddr) {
		this.dsAddr = dsAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.PT_LAT
	 * @return  the value of BNF_EVENT.PT_LAT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public BigDecimal getPtLat() {
		return ptLat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.PT_LAT
	 * @param ptLat  the value for BNF_EVENT.PT_LAT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setPtLat(BigDecimal ptLat) {
		this.ptLat = ptLat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.PT_LONG
	 * @return  the value of BNF_EVENT.PT_LONG
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public BigDecimal getPtLong() {
		return ptLong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.PT_LONG
	 * @param ptLong  the value for BNF_EVENT.PT_LONG
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setPtLong(BigDecimal ptLong) {
		this.ptLong = ptLong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_WINNER_NOTICE
	 * @return  the value of BNF_EVENT.DS_WINNER_NOTICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsWinnerNotice() {
		return dsWinnerNotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_WINNER_NOTICE
	 * @param dsWinnerNotice  the value for BNF_EVENT.DS_WINNER_NOTICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsWinnerNotice(String dsWinnerNotice) {
		this.dsWinnerNotice = dsWinnerNotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.AM_PRICE
	 * @return  the value of BNF_EVENT.AM_PRICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getAmPrice() {
		return amPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.AM_PRICE
	 * @param amPrice  the value for BNF_EVENT.AM_PRICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setAmPrice(String amPrice) {
		this.amPrice = amPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_PRICE
	 * @return  the value of BNF_EVENT.DS_PRICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsPrice() {
		return dsPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_PRICE
	 * @param dsPrice  the value for BNF_EVENT.DS_PRICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsPrice(String dsPrice) {
		this.dsPrice = dsPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_REFUND
	 * @return  the value of BNF_EVENT.DS_REFUND
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsRefund() {
		return dsRefund;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_REFUND
	 * @param dsRefund  the value for BNF_EVENT.DS_REFUND
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsRefund(String dsRefund) {
		this.dsRefund = dsRefund;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DT_REG
	 * @return  the value of BNF_EVENT.DT_REG
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public Date getDtReg() {
		return dtReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DT_REG
	 * @param dtReg  the value for BNF_EVENT.DT_REG
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDtReg(Date dtReg) {
		this.dtReg = dtReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_PERSONS
	 * @return  the value of BNF_EVENT.DS_PERSONS
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsPersons() {
		return dsPersons;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_PERSONS
	 * @param dsPersons  the value for BNF_EVENT.DS_PERSONS
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsPersons(String dsPersons) {
		this.dsPersons = dsPersons;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_ABOUT
	 * @return  the value of BNF_EVENT.DS_ABOUT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsAbout() {
		return dsAbout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_ABOUT
	 * @param dsAbout  the value for BNF_EVENT.DS_ABOUT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsAbout(String dsAbout) {
		this.dsAbout = dsAbout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_FOR
	 * @return  the value of BNF_EVENT.DS_FOR
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsFor() {
		return dsFor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_FOR
	 * @param dsFor  the value for BNF_EVENT.DS_FOR
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsFor(String dsFor) {
		this.dsFor = dsFor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_CURRICULUM
	 * @return  the value of BNF_EVENT.DS_CURRICULUM
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsCurriculum() {
		return dsCurriculum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_CURRICULUM
	 * @param dsCurriculum  the value for BNF_EVENT.DS_CURRICULUM
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsCurriculum(String dsCurriculum) {
		this.dsCurriculum = dsCurriculum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_BENEFIT
	 * @return  the value of BNF_EVENT.DS_BENEFIT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsBenefit() {
		return dsBenefit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_BENEFIT
	 * @param dsBenefit  the value for BNF_EVENT.DS_BENEFIT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsBenefit(String dsBenefit) {
		this.dsBenefit = dsBenefit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_APPLY
	 * @return  the value of BNF_EVENT.DS_APPLY
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsApply() {
		return dsApply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_APPLY
	 * @param dsApply  the value for BNF_EVENT.DS_APPLY
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsApply(String dsApply) {
		this.dsApply = dsApply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_NOTICE
	 * @return  the value of BNF_EVENT.DS_NOTICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsNotice() {
		return dsNotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_NOTICE
	 * @param dsNotice  the value for BNF_EVENT.DS_NOTICE
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsNotice(String dsNotice) {
		this.dsNotice = dsNotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BNF_EVENT.DS_PARKING
	 * @return  the value of BNF_EVENT.DS_PARKING
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public String getDsParking() {
		return dsParking;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BNF_EVENT.DS_PARKING
	 * @param dsParking  the value for BNF_EVENT.DS_PARKING
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	public void setDsParking(String dsParking) {
		this.dsParking = dsParking;
	}
	
	private String question3rd;

	public String getQuestion3rd() {
		return question3rd;
	}

	public void setQuestion3rd(String question3rd) {
		this.question3rd = question3rd;
	}

	

}