package com.kinzr.apellian.entity.model;

public class BnfEventBnfImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_BNF_IMAGES.ID_BNF_EVENT_BNF_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private Integer idBnfEventBnfImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_BNF_IMAGES.ID_BNF_EVENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private Integer idBnfEvent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_BNF_IMAGES.NM_BNF_EVENT_BNF_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private String nmBnfEventBnfImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_BNF_IMAGES.URL_BNF_EVENT_BNF_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private String urlBnfEventBnfImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_BNF_IMAGES.ID_BNF_EVENT_BNF_IMAGE
     *
     * @return the value of BNF_EVENT_BNF_IMAGES.ID_BNF_EVENT_BNF_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public Integer getIdBnfEventBnfImage() {
        return idBnfEventBnfImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_BNF_IMAGES.ID_BNF_EVENT_BNF_IMAGE
     *
     * @param idBnfEventBnfImage the value for BNF_EVENT_BNF_IMAGES.ID_BNF_EVENT_BNF_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setIdBnfEventBnfImage(Integer idBnfEventBnfImage) {
        this.idBnfEventBnfImage = idBnfEventBnfImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_BNF_IMAGES.ID_BNF_EVENT
     *
     * @return the value of BNF_EVENT_BNF_IMAGES.ID_BNF_EVENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public Integer getIdBnfEvent() {
        return idBnfEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_BNF_IMAGES.ID_BNF_EVENT
     *
     * @param idBnfEvent the value for BNF_EVENT_BNF_IMAGES.ID_BNF_EVENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setIdBnfEvent(Integer idBnfEvent) {
        this.idBnfEvent = idBnfEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_BNF_IMAGES.NM_BNF_EVENT_BNF_IMAGE
     *
     * @return the value of BNF_EVENT_BNF_IMAGES.NM_BNF_EVENT_BNF_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public String getNmBnfEventBnfImage() {
        return nmBnfEventBnfImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_BNF_IMAGES.NM_BNF_EVENT_BNF_IMAGE
     *
     * @param nmBnfEventBnfImage the value for BNF_EVENT_BNF_IMAGES.NM_BNF_EVENT_BNF_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setNmBnfEventBnfImage(String nmBnfEventBnfImage) {
        this.nmBnfEventBnfImage = nmBnfEventBnfImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_BNF_IMAGES.URL_BNF_EVENT_BNF_IMAGE
     *
     * @return the value of BNF_EVENT_BNF_IMAGES.URL_BNF_EVENT_BNF_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public String getUrlBnfEventBnfImage() {
        return urlBnfEventBnfImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_BNF_IMAGES.URL_BNF_EVENT_BNF_IMAGE
     *
     * @param urlBnfEventBnfImage the value for BNF_EVENT_BNF_IMAGES.URL_BNF_EVENT_BNF_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setUrlBnfEventBnfImage(String urlBnfEventBnfImage) {
        this.urlBnfEventBnfImage = urlBnfEventBnfImage;
    }
}