package com.kinzr.apellian.entity.model;

public class BnfEventImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_IMAGES.ID_BNF_EVENT_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private Integer idBnfEventImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_IMAGES.ID_BNF_EVENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private Integer idBnfEvent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_IMAGES.NM_BNF_EVENT_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private String nmBnfEventImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BNF_EVENT_IMAGES.URL_BNF_EVENT_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    private String urlBnfEventImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_IMAGES.ID_BNF_EVENT_IMAGE
     *
     * @return the value of BNF_EVENT_IMAGES.ID_BNF_EVENT_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public Integer getIdBnfEventImage() {
        return idBnfEventImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_IMAGES.ID_BNF_EVENT_IMAGE
     *
     * @param idBnfEventImage the value for BNF_EVENT_IMAGES.ID_BNF_EVENT_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setIdBnfEventImage(Integer idBnfEventImage) {
        this.idBnfEventImage = idBnfEventImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_IMAGES.ID_BNF_EVENT
     *
     * @return the value of BNF_EVENT_IMAGES.ID_BNF_EVENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public Integer getIdBnfEvent() {
        return idBnfEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_IMAGES.ID_BNF_EVENT
     *
     * @param idBnfEvent the value for BNF_EVENT_IMAGES.ID_BNF_EVENT
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setIdBnfEvent(Integer idBnfEvent) {
        this.idBnfEvent = idBnfEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_IMAGES.NM_BNF_EVENT_IMAGE
     *
     * @return the value of BNF_EVENT_IMAGES.NM_BNF_EVENT_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public String getNmBnfEventImage() {
        return nmBnfEventImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_IMAGES.NM_BNF_EVENT_IMAGE
     *
     * @param nmBnfEventImage the value for BNF_EVENT_IMAGES.NM_BNF_EVENT_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setNmBnfEventImage(String nmBnfEventImage) {
        this.nmBnfEventImage = nmBnfEventImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BNF_EVENT_IMAGES.URL_BNF_EVENT_IMAGE
     *
     * @return the value of BNF_EVENT_IMAGES.URL_BNF_EVENT_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public String getUrlBnfEventImage() {
        return urlBnfEventImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BNF_EVENT_IMAGES.URL_BNF_EVENT_IMAGE
     *
     * @param urlBnfEventImage the value for BNF_EVENT_IMAGES.URL_BNF_EVENT_IMAGE
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    public void setUrlBnfEventImage(String urlBnfEventImage) {
        this.urlBnfEventImage = urlBnfEventImage;
    }
}