package com.kinzr.apellian.entity.model;

import java.util.Date;

public class Board {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.ID_BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Long idBoard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.TY_BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String tyBoard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynPublish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.ID_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String idReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Date dtReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.NM_BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String nmBoard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.ID_BOARD
     *
     * @return the value of BOARD.ID_BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Long getIdBoard() {
        return idBoard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.ID_BOARD
     *
     * @param idBoard the value for BOARD.ID_BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdBoard(Long idBoard) {
        this.idBoard = idBoard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.TY_BOARD
     *
     * @return the value of BOARD.TY_BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getTyBoard() {
        return tyBoard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.TY_BOARD
     *
     * @param tyBoard the value for BOARD.TY_BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setTyBoard(String tyBoard) {
        this.tyBoard = tyBoard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.YN_PUBLISH
     *
     * @return the value of BOARD.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnPublish() {
        return ynPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.YN_PUBLISH
     *
     * @param ynPublish the value for BOARD.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnPublish(String ynPublish) {
        this.ynPublish = ynPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.ID_REG
     *
     * @return the value of BOARD.ID_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getIdReg() {
        return idReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.ID_REG
     *
     * @param idReg the value for BOARD.ID_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdReg(String idReg) {
        this.idReg = idReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.DT_REG
     *
     * @return the value of BOARD.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Date getDtReg() {
        return dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.DT_REG
     *
     * @param dtReg the value for BOARD.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDtReg(Date dtReg) {
        this.dtReg = dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.NM_BOARD
     *
     * @return the value of BOARD.NM_BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getNmBoard() {
        return nmBoard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.NM_BOARD
     *
     * @param nmBoard the value for BOARD.NM_BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNmBoard(String nmBoard) {
        this.nmBoard = nmBoard;
    }
}