package com.kinzr.apellian.entity.model;

public class CdCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_CATEGORY.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer cdCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_CATEGORY.NM_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String nmCategory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_CATEGORY.CD_CATEGORY
     *
     * @return the value of CD_CATEGORY.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdCategory() {
        return cdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_CATEGORY.CD_CATEGORY
     *
     * @param cdCategory the value for CD_CATEGORY.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdCategory(Integer cdCategory) {
        this.cdCategory = cdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_CATEGORY.NM_CATEGORY
     *
     * @return the value of CD_CATEGORY.NM_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getNmCategory() {
        return nmCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_CATEGORY.NM_CATEGORY
     *
     * @param nmCategory the value for CD_CATEGORY.NM_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNmCategory(String nmCategory) {
        this.nmCategory = nmCategory;
    }
}