package com.kinzr.apellian.entity.model;

public class CdCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_COMPANY.CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer cdCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_COMPANY.NM_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String nmCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_COMPANY.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer cdCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_COMPANY.ID_USER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String idUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_COMPANY.DS_OP_HOUR
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsOpHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_COMPANY.DS_ADDR
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_COMPANY.DS_CONTACT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_COMPANY.URL_COMPANY_IMG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String urlCompanyImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_COMPANY.ID_INSTAGRAM
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String idInstagram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_COMPANY.DS_ABOUT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsAbout;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_COMPANY.CD_COMPANY
     *
     * @return the value of CD_COMPANY.CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdCompany() {
        return cdCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_COMPANY.CD_COMPANY
     *
     * @param cdCompany the value for CD_COMPANY.CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdCompany(Integer cdCompany) {
        this.cdCompany = cdCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_COMPANY.NM_COMPANY
     *
     * @return the value of CD_COMPANY.NM_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getNmCompany() {
        return nmCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_COMPANY.NM_COMPANY
     *
     * @param nmCompany the value for CD_COMPANY.NM_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNmCompany(String nmCompany) {
        this.nmCompany = nmCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_COMPANY.CD_CATEGORY
     *
     * @return the value of CD_COMPANY.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdCategory() {
        return cdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_COMPANY.CD_CATEGORY
     *
     * @param cdCategory the value for CD_COMPANY.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdCategory(Integer cdCategory) {
        this.cdCategory = cdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_COMPANY.ID_USER
     *
     * @return the value of CD_COMPANY.ID_USER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_COMPANY.ID_USER
     *
     * @param idUser the value for CD_COMPANY.ID_USER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_COMPANY.DS_OP_HOUR
     *
     * @return the value of CD_COMPANY.DS_OP_HOUR
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsOpHour() {
        return dsOpHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_COMPANY.DS_OP_HOUR
     *
     * @param dsOpHour the value for CD_COMPANY.DS_OP_HOUR
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsOpHour(String dsOpHour) {
        this.dsOpHour = dsOpHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_COMPANY.DS_ADDR
     *
     * @return the value of CD_COMPANY.DS_ADDR
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsAddr() {
        return dsAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_COMPANY.DS_ADDR
     *
     * @param dsAddr the value for CD_COMPANY.DS_ADDR
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsAddr(String dsAddr) {
        this.dsAddr = dsAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_COMPANY.DS_CONTACT
     *
     * @return the value of CD_COMPANY.DS_CONTACT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsContact() {
        return dsContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_COMPANY.DS_CONTACT
     *
     * @param dsContact the value for CD_COMPANY.DS_CONTACT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsContact(String dsContact) {
        this.dsContact = dsContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_COMPANY.URL_COMPANY_IMG
     *
     * @return the value of CD_COMPANY.URL_COMPANY_IMG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getUrlCompanyImg() {
        return urlCompanyImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_COMPANY.URL_COMPANY_IMG
     *
     * @param urlCompanyImg the value for CD_COMPANY.URL_COMPANY_IMG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setUrlCompanyImg(String urlCompanyImg) {
        this.urlCompanyImg = urlCompanyImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_COMPANY.ID_INSTAGRAM
     *
     * @return the value of CD_COMPANY.ID_INSTAGRAM
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getIdInstagram() {
        return idInstagram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_COMPANY.ID_INSTAGRAM
     *
     * @param idInstagram the value for CD_COMPANY.ID_INSTAGRAM
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdInstagram(String idInstagram) {
        this.idInstagram = idInstagram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_COMPANY.DS_ABOUT
     *
     * @return the value of CD_COMPANY.DS_ABOUT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsAbout() {
        return dsAbout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_COMPANY.DS_ABOUT
     *
     * @param dsAbout the value for CD_COMPANY.DS_ABOUT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsAbout(String dsAbout) {
        this.dsAbout = dsAbout;
    }
}