package com.kinzr.apellian.entity.model;

public class CdMagazineCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_MAGAZINE_CATEGORY.CD_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer cdMagazineCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_MAGAZINE_CATEGORY.NM_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String nmMagazineCategory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_MAGAZINE_CATEGORY.CD_MAGAZINE_CATEGORY
     *
     * @return the value of CD_MAGAZINE_CATEGORY.CD_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdMagazineCategory() {
        return cdMagazineCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_MAGAZINE_CATEGORY.CD_MAGAZINE_CATEGORY
     *
     * @param cdMagazineCategory the value for CD_MAGAZINE_CATEGORY.CD_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdMagazineCategory(Integer cdMagazineCategory) {
        this.cdMagazineCategory = cdMagazineCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_MAGAZINE_CATEGORY.NM_MAGAZINE_CATEGORY
     *
     * @return the value of CD_MAGAZINE_CATEGORY.NM_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getNmMagazineCategory() {
        return nmMagazineCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_MAGAZINE_CATEGORY.NM_MAGAZINE_CATEGORY
     *
     * @param nmMagazineCategory the value for CD_MAGAZINE_CATEGORY.NM_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNmMagazineCategory(String nmMagazineCategory) {
        this.nmMagazineCategory = nmMagazineCategory;
    }
}