package com.kinzr.apellian.entity.model;

public class CdPkgTheme {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_PKG_THEME.CD_PKG_THEME
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer cdPkgTheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_PKG_THEME.NM_PKG_THEME
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String nmPkgTheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_PKG_THEME.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer noOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_PKG_THEME.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynPublish;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_PKG_THEME.CD_PKG_THEME
     *
     * @return the value of CD_PKG_THEME.CD_PKG_THEME
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdPkgTheme() {
        return cdPkgTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_PKG_THEME.CD_PKG_THEME
     *
     * @param cdPkgTheme the value for CD_PKG_THEME.CD_PKG_THEME
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdPkgTheme(Integer cdPkgTheme) {
        this.cdPkgTheme = cdPkgTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_PKG_THEME.NM_PKG_THEME
     *
     * @return the value of CD_PKG_THEME.NM_PKG_THEME
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getNmPkgTheme() {
        return nmPkgTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_PKG_THEME.NM_PKG_THEME
     *
     * @param nmPkgTheme the value for CD_PKG_THEME.NM_PKG_THEME
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNmPkgTheme(String nmPkgTheme) {
        this.nmPkgTheme = nmPkgTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_PKG_THEME.NO_ORDER
     *
     * @return the value of CD_PKG_THEME.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getNoOrder() {
        return noOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_PKG_THEME.NO_ORDER
     *
     * @param noOrder the value for CD_PKG_THEME.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNoOrder(Integer noOrder) {
        this.noOrder = noOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_PKG_THEME.YN_PUBLISH
     *
     * @return the value of CD_PKG_THEME.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnPublish() {
        return ynPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_PKG_THEME.YN_PUBLISH
     *
     * @param ynPublish the value for CD_PKG_THEME.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnPublish(String ynPublish) {
        this.ynPublish = ynPublish;
    }
}