package com.kinzr.apellian.entity.model;

public class CdWedAccessory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_ACCESSORY.ID_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idWeddingHall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_ACCESSORY.ID_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idAccessory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_ACCESSORY.DS_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsAccessory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_ACCESSORY.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer noOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_ACCESSORY.ID_REF
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String idRef;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_ACCESSORY.ID_WEDDING_HALL
     *
     * @return the value of CD_WED_ACCESSORY.ID_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdWeddingHall() {
        return idWeddingHall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_ACCESSORY.ID_WEDDING_HALL
     *
     * @param idWeddingHall the value for CD_WED_ACCESSORY.ID_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdWeddingHall(Integer idWeddingHall) {
        this.idWeddingHall = idWeddingHall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_ACCESSORY.ID_ACCESSORY
     *
     * @return the value of CD_WED_ACCESSORY.ID_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdAccessory() {
        return idAccessory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_ACCESSORY.ID_ACCESSORY
     *
     * @param idAccessory the value for CD_WED_ACCESSORY.ID_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdAccessory(Integer idAccessory) {
        this.idAccessory = idAccessory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_ACCESSORY.DS_ACCESSORY
     *
     * @return the value of CD_WED_ACCESSORY.DS_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsAccessory() {
        return dsAccessory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_ACCESSORY.DS_ACCESSORY
     *
     * @param dsAccessory the value for CD_WED_ACCESSORY.DS_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsAccessory(String dsAccessory) {
        this.dsAccessory = dsAccessory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_ACCESSORY.NO_ORDER
     *
     * @return the value of CD_WED_ACCESSORY.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getNoOrder() {
        return noOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_ACCESSORY.NO_ORDER
     *
     * @param noOrder the value for CD_WED_ACCESSORY.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNoOrder(Integer noOrder) {
        this.noOrder = noOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_ACCESSORY.ID_REF
     *
     * @return the value of CD_WED_ACCESSORY.ID_REF
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getIdRef() {
        return idRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_ACCESSORY.ID_REF
     *
     * @param idRef the value for CD_WED_ACCESSORY.ID_REF
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdRef(String idRef) {
        this.idRef = idRef;
    }
}