package com.kinzr.apellian.entity.model;

public class CdWedCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_CATEGORY.ID_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idWeddingHall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_CATEGORY.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer cdCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_CATEGORY.DS_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_CATEGORY.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer noOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_CATEGORY.ID_REF
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String idRef;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_CATEGORY.ID_WEDDING_HALL
     *
     * @return the value of CD_WED_CATEGORY.ID_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdWeddingHall() {
        return idWeddingHall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_CATEGORY.ID_WEDDING_HALL
     *
     * @param idWeddingHall the value for CD_WED_CATEGORY.ID_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdWeddingHall(Integer idWeddingHall) {
        this.idWeddingHall = idWeddingHall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_CATEGORY.CD_CATEGORY
     *
     * @return the value of CD_WED_CATEGORY.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdCategory() {
        return cdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_CATEGORY.CD_CATEGORY
     *
     * @param cdCategory the value for CD_WED_CATEGORY.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdCategory(Integer cdCategory) {
        this.cdCategory = cdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_CATEGORY.DS_CATEGORY
     *
     * @return the value of CD_WED_CATEGORY.DS_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsCategory() {
        return dsCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_CATEGORY.DS_CATEGORY
     *
     * @param dsCategory the value for CD_WED_CATEGORY.DS_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsCategory(String dsCategory) {
        this.dsCategory = dsCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_CATEGORY.NO_ORDER
     *
     * @return the value of CD_WED_CATEGORY.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getNoOrder() {
        return noOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_CATEGORY.NO_ORDER
     *
     * @param noOrder the value for CD_WED_CATEGORY.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNoOrder(Integer noOrder) {
        this.noOrder = noOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_CATEGORY.ID_REF
     *
     * @return the value of CD_WED_CATEGORY.ID_REF
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getIdRef() {
        return idRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_CATEGORY.ID_REF
     *
     * @param idRef the value for CD_WED_CATEGORY.ID_REF
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdRef(String idRef) {
        this.idRef = idRef;
    }
}