package com.kinzr.apellian.entity.model;

public class CdWedOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_OPTION.ID_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idWeddingHall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_OPTION.ID_OPTION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idOption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_OPTION.DS_OPTION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsOption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_OPTION.AM_PRICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer amPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_OPTION.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer noOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CD_WED_OPTION.ID_REF
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String idRef;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_OPTION.ID_WEDDING_HALL
     *
     * @return the value of CD_WED_OPTION.ID_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdWeddingHall() {
        return idWeddingHall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_OPTION.ID_WEDDING_HALL
     *
     * @param idWeddingHall the value for CD_WED_OPTION.ID_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdWeddingHall(Integer idWeddingHall) {
        this.idWeddingHall = idWeddingHall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_OPTION.ID_OPTION
     *
     * @return the value of CD_WED_OPTION.ID_OPTION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdOption() {
        return idOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_OPTION.ID_OPTION
     *
     * @param idOption the value for CD_WED_OPTION.ID_OPTION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdOption(Integer idOption) {
        this.idOption = idOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_OPTION.DS_OPTION
     *
     * @return the value of CD_WED_OPTION.DS_OPTION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsOption() {
        return dsOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_OPTION.DS_OPTION
     *
     * @param dsOption the value for CD_WED_OPTION.DS_OPTION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsOption(String dsOption) {
        this.dsOption = dsOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_OPTION.AM_PRICE
     *
     * @return the value of CD_WED_OPTION.AM_PRICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getAmPrice() {
        return amPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_OPTION.AM_PRICE
     *
     * @param amPrice the value for CD_WED_OPTION.AM_PRICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setAmPrice(Integer amPrice) {
        this.amPrice = amPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_OPTION.NO_ORDER
     *
     * @return the value of CD_WED_OPTION.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getNoOrder() {
        return noOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_OPTION.NO_ORDER
     *
     * @param noOrder the value for CD_WED_OPTION.NO_ORDER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNoOrder(Integer noOrder) {
        this.noOrder = noOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CD_WED_OPTION.ID_REF
     *
     * @return the value of CD_WED_OPTION.ID_REF
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getIdRef() {
        return idRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CD_WED_OPTION.ID_REF
     *
     * @param idRef the value for CD_WED_OPTION.ID_REF
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdRef(String idRef) {
        this.idRef = idRef;
    }
}