package com.kinzr.apellian.entity.model;

import java.util.Date;

public class MagazineSavedList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE_SAVED_LIST.ID_USER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String idUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE_SAVED_LIST.ID_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idMagazine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE_SAVED_LIST.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Date dtReg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE_SAVED_LIST.ID_USER
     *
     * @return the value of MAGAZINE_SAVED_LIST.ID_USER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE_SAVED_LIST.ID_USER
     *
     * @param idUser the value for MAGAZINE_SAVED_LIST.ID_USER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE_SAVED_LIST.ID_MAGAZINE
     *
     * @return the value of MAGAZINE_SAVED_LIST.ID_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdMagazine() {
        return idMagazine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE_SAVED_LIST.ID_MAGAZINE
     *
     * @param idMagazine the value for MAGAZINE_SAVED_LIST.ID_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdMagazine(Integer idMagazine) {
        this.idMagazine = idMagazine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE_SAVED_LIST.DT_REG
     *
     * @return the value of MAGAZINE_SAVED_LIST.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Date getDtReg() {
        return dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE_SAVED_LIST.DT_REG
     *
     * @param dtReg the value for MAGAZINE_SAVED_LIST.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDtReg(Date dtReg) {
        this.dtReg = dtReg;
    }
}