package com.kinzr.apellian.entity.model;

import java.util.Date;

public class Magazine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE.ID_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idMagazine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE.NM_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String nmMagazine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE.DS_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsMagazine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE.CT_VIEW
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Long ctView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynPublish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE.ID_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String idReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Date dtReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE.DS_CONTENT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE.URL_BLOG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String urlBlog;
    
    
    private String urlImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE.ID_MAGAZINE
     *
     * @return the value of MAGAZINE.ID_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdMagazine() {
        return idMagazine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE.ID_MAGAZINE
     *
     * @param idMagazine the value for MAGAZINE.ID_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdMagazine(Integer idMagazine) {
        this.idMagazine = idMagazine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE.NM_MAGAZINE
     *
     * @return the value of MAGAZINE.NM_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getNmMagazine() {
        return nmMagazine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE.NM_MAGAZINE
     *
     * @param nmMagazine the value for MAGAZINE.NM_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNmMagazine(String nmMagazine) {
        this.nmMagazine = nmMagazine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE.DS_MAGAZINE
     *
     * @return the value of MAGAZINE.DS_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsMagazine() {
        return dsMagazine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE.DS_MAGAZINE
     *
     * @param dsMagazine the value for MAGAZINE.DS_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsMagazine(String dsMagazine) {
        this.dsMagazine = dsMagazine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE.CT_VIEW
     *
     * @return the value of MAGAZINE.CT_VIEW
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Long getCtView() {
        return ctView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE.CT_VIEW
     *
     * @param ctView the value for MAGAZINE.CT_VIEW
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCtView(Long ctView) {
        this.ctView = ctView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE.YN_PUBLISH
     *
     * @return the value of MAGAZINE.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnPublish() {
        return ynPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE.YN_PUBLISH
     *
     * @param ynPublish the value for MAGAZINE.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnPublish(String ynPublish) {
        this.ynPublish = ynPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE.ID_REG
     *
     * @return the value of MAGAZINE.ID_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getIdReg() {
        return idReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE.ID_REG
     *
     * @param idReg the value for MAGAZINE.ID_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdReg(String idReg) {
        this.idReg = idReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE.DT_REG
     *
     * @return the value of MAGAZINE.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Date getDtReg() {
        return dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE.DT_REG
     *
     * @param dtReg the value for MAGAZINE.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDtReg(Date dtReg) {
        this.dtReg = dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE.DS_CONTENT
     *
     * @return the value of MAGAZINE.DS_CONTENT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsContent() {
        return dsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE.DS_CONTENT
     *
     * @param dsContent the value for MAGAZINE.DS_CONTENT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsContent(String dsContent) {
        this.dsContent = dsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE.URL_BLOG
     *
     * @return the value of MAGAZINE.URL_BLOG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getUrlBlog() {
        return urlBlog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE.URL_BLOG
     *
     * @param urlBlog the value for MAGAZINE.URL_BLOG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setUrlBlog(String urlBlog) {
        this.urlBlog = urlBlog;
    }
    
    public String getUrlImg() {
        return urlImg;
    }
    public void setUrlImg(String  urlImg) {
        this.urlImg = urlImg;
    }

}