package com.kinzr.apellian.entity.model;

public class MagazineCategoryList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE_CATEGORY_LIST.ID_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idMagazine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAGAZINE_CATEGORY_LIST.CD_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer cdMagazineCategory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE_CATEGORY_LIST.ID_MAGAZINE
     *
     * @return the value of MAGAZINE_CATEGORY_LIST.ID_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdMagazine() {
        return idMagazine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE_CATEGORY_LIST.ID_MAGAZINE
     *
     * @param idMagazine the value for MAGAZINE_CATEGORY_LIST.ID_MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdMagazine(Integer idMagazine) {
        this.idMagazine = idMagazine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAGAZINE_CATEGORY_LIST.CD_MAGAZINE_CATEGORY
     *
     * @return the value of MAGAZINE_CATEGORY_LIST.CD_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdMagazineCategory() {
        return cdMagazineCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAGAZINE_CATEGORY_LIST.CD_MAGAZINE_CATEGORY
     *
     * @param cdMagazineCategory the value for MAGAZINE_CATEGORY_LIST.CD_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdMagazineCategory(Integer cdMagazineCategory) {
        this.cdMagazineCategory = cdMagazineCategory;
    }
}