package com.kinzr.apellian.entity.model;

public class MyWedOption {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_OPTION.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Long idWedding;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_OPTION.ID_OPTION
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Integer idOption;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_OPTION.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Integer idWeddingHall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_OPTION.AM_PRICE
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Integer amPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_OPTION.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private String idRef;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_OPTION.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private String dsOption;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_OPTION.ID_WEDDING
	 * @return  the value of MY_WED_OPTION.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Long getIdWedding() {
		return idWedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_OPTION.ID_WEDDING
	 * @param idWedding  the value for MY_WED_OPTION.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdWedding(Long idWedding) {
		this.idWedding = idWedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_OPTION.ID_OPTION
	 * @return  the value of MY_WED_OPTION.ID_OPTION
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Integer getIdOption() {
		return idOption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_OPTION.ID_OPTION
	 * @param idOption  the value for MY_WED_OPTION.ID_OPTION
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdOption(Integer idOption) {
		this.idOption = idOption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_OPTION.ID_WEDDING_HALL
	 * @return  the value of MY_WED_OPTION.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Integer getIdWeddingHall() {
		return idWeddingHall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_OPTION.ID_WEDDING_HALL
	 * @param idWeddingHall  the value for MY_WED_OPTION.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdWeddingHall(Integer idWeddingHall) {
		this.idWeddingHall = idWeddingHall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_OPTION.AM_PRICE
	 * @return  the value of MY_WED_OPTION.AM_PRICE
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Integer getAmPrice() {
		return amPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_OPTION.AM_PRICE
	 * @param amPrice  the value for MY_WED_OPTION.AM_PRICE
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setAmPrice(Integer amPrice) {
		this.amPrice = amPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_OPTION.ID_REF
	 * @return  the value of MY_WED_OPTION.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getIdRef() {
		return idRef;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_OPTION.ID_REF
	 * @param idRef  the value for MY_WED_OPTION.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdRef(String idRef) {
		this.idRef = idRef;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_OPTION.ID_REF
	 * @return  the value of MY_WED_OPTION.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getDsOption() {
		return dsOption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_OPTION.ID_REF
	 * @param idRef  the value for MY_WED_OPTION.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setDsOption(String dsOption) {
		this.dsOption = dsOption;
	}
	
}