package com.kinzr.apellian.entity.model;

public class MyWedCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_CATEGORY.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Long idWedding;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_CATEGORY.CD_CATEGORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Integer cdCategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_CATEGORY.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Integer idWeddingHall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_CATEGORY.CD_COMPANY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Integer cdCompany;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_CATEGORY.AM_PRICE
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Long amPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_CATEGORY.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private String idRef;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_CATEGORY.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	
	private String nmCategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_CATEGORY.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	
	private String nmCompany;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_CATEGORY.ID_WEDDING
	 * @return  the value of MY_WED_CATEGORY.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Long getIdWedding() {
		return idWedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_CATEGORY.ID_WEDDING
	 * @param idWedding  the value for MY_WED_CATEGORY.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdWedding(Long idWedding) {
		this.idWedding = idWedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_CATEGORY.CD_CATEGORY
	 * @return  the value of MY_WED_CATEGORY.CD_CATEGORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Integer getCdCategory() {
		return cdCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_CATEGORY.CD_CATEGORY
	 * @param cdCategory  the value for MY_WED_CATEGORY.CD_CATEGORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setCdCategory(Integer cdCategory) {
		this.cdCategory = cdCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_CATEGORY.ID_WEDDING_HALL
	 * @return  the value of MY_WED_CATEGORY.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Integer getIdWeddingHall() {
		return idWeddingHall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_CATEGORY.ID_WEDDING_HALL
	 * @param idWeddingHall  the value for MY_WED_CATEGORY.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdWeddingHall(Integer idWeddingHall) {
		this.idWeddingHall = idWeddingHall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_CATEGORY.CD_COMPANY
	 * @return  the value of MY_WED_CATEGORY.CD_COMPANY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Integer getCdCompany() {
		return cdCompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_CATEGORY.CD_COMPANY
	 * @param cdCompany  the value for MY_WED_CATEGORY.CD_COMPANY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setCdCompany(Integer cdCompany) {
		this.cdCompany = cdCompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_CATEGORY.AM_PRICE
	 * @return  the value of MY_WED_CATEGORY.AM_PRICE
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Long getAmPrice() {
		return amPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_CATEGORY.AM_PRICE
	 * @param amPrice  the value for MY_WED_CATEGORY.AM_PRICE
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setAmPrice(Long amPrice) {
		this.amPrice = amPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_CATEGORY.ID_REF
	 * @return  the value of MY_WED_CATEGORY.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getIdRef() {
		return idRef;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_CATEGORY.ID_REF
	 * @param idRef  the value for MY_WED_CATEGORY.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdRef(String idRef) {
		this.idRef = idRef;
	}
	

	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_CATEGORY.ID_REF
	 * @return  the value of MY_WED_CATEGORY.NM_CATEGORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getNmCategory() {
		return nmCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_CATEGORY.ID_REF
	 * @param idRef  the value for MY_WED_CATEGORY.NM_CATEGORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setNmCategory(String nmCategory) {
		this.nmCategory = nmCategory;
	}
		
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_CATEGORY.ID_REF
	 * @return  the value of MY_WED_CATEGORY.NM_COMPANY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getNmCompany() {
		return nmCompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_CATEGORY.ID_REF
	 * @param idRef  the value for MY_WED_CATEGORY.NM_COMPANY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setNmCompany(String nmCompany) {
		this.nmCompany = nmCompany;
	}
	

	

	
}