package com.kinzr.apellian.entity.model;

import java.util.Date;

public class MyWed {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Long idWedding;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private String idWeddingHall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED.NM_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private String nmWeddingHall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private String idRef;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED.ID_USER
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private String idUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED.NM_PARTNER
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private String nmPartner;
	private String nmMan;
	private String nmWoman;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED.DT_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Date dtWedding;
	private String tmWedding;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED.URL_CONTRACT
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private String urlContract;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED.DT_REG
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Date dtReg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED.ID_WEDDING
	 * @return  the value of MY_WED.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Long getIdWedding() {
		return idWedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED.ID_WEDDING
	 * @param idWedding  the value for MY_WED.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdWedding(Long idWedding) {
		this.idWedding = idWedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED.ID_WEDDING_HALL
	 * @return  the value of MY_WED.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getIdWeddingHall() {
		return idWeddingHall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED.ID_WEDDING_HALL
	 * @param idWeddingHall  the value for MY_WED.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdWeddingHall(String idWeddingHall) {
		this.idWeddingHall = idWeddingHall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED.NM_WEDDING_HALL
	 * @return  the value of MY_WED.NM_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getNmWeddingHall() {
		return nmWeddingHall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED.NM_WEDDING_HALL
	 * @param nmWeddingHall  the value for MY_WED.NM_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setNmWeddingHall(String nmWeddingHall) {
		this.nmWeddingHall = nmWeddingHall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED.ID_REF
	 * @return  the value of MY_WED.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getIdRef() {
		return idRef;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED.ID_REF
	 * @param idRef  the value for MY_WED.ID_REF
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdRef(String idRef) {
		this.idRef = idRef;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED.ID_USER
	 * @return  the value of MY_WED.ID_USER
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getIdUser() {
		return idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED.ID_USER
	 * @param idUser  the value for MY_WED.ID_USER
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED.NM_PARTNER
	 * @return  the value of MY_WED.NM_PARTNER
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getNmPartner() {
		return nmPartner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED.NM_PARTNER
	 * @param nmPartner  the value for MY_WED.NM_PARTNER
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setNmPartner(String nmPartner) {
		this.nmPartner = nmPartner;
	}

	public String getNmMan() {
		return nmMan;
	}

	public void setNmMan(String nmMan) {
		this.nmMan = nmMan;
	}

	public String getNmWoman() {
		return nmWoman;
	}

	public void setNmWoman(String nmWoman) {
		this.nmWoman = nmWoman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED.DT_WEDDING
	 * @return  the value of MY_WED.DT_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Date getDtWedding() {
		return dtWedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED.DT_WEDDING
	 * @param dtWedding  the value for MY_WED.DT_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setDtWedding(Date dtWedding) {
		this.dtWedding = dtWedding;
	}
	
	public String getTmWedding() {
		return tmWedding;
	}
	public void setTmWedding(String tmWedding) {
		this.tmWedding = tmWedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED.URL_CONTRACT
	 * @return  the value of MY_WED.URL_CONTRACT
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getUrlContract() {
		return urlContract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED.URL_CONTRACT
	 * @param urlContract  the value for MY_WED.URL_CONTRACT
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setUrlContract(String urlContract) {
		this.urlContract = urlContract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED.DT_REG
	 * @return  the value of MY_WED.DT_REG
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Date getDtReg() {
		return dtReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED.DT_REG
	 * @param dtReg  the value for MY_WED.DT_REG
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setDtReg(Date dtReg) {
		this.dtReg = dtReg;
	}
}