package com.kinzr.apellian.entity.model;

public class MyWedAccessory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_ACCESSORY.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Long idWedding;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_ACCESSORY.ID_ACCESSORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Integer idAccessory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_ACCESSORY.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private Integer idWeddingHall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MY_WED_ACCESSORY.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	private String dsAccessory;
    
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_ACCESSORY.ID_WEDDING
	 * @return  the value of MY_WED_ACCESSORY.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Long getIdWedding() {
		return idWedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_ACCESSORY.ID_WEDDING
	 * @param idWedding  the value for MY_WED_ACCESSORY.ID_WEDDING
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdWedding(Long idWedding) {
		this.idWedding = idWedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_ACCESSORY.ID_ACCESSORY
	 * @return  the value of MY_WED_ACCESSORY.ID_ACCESSORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Integer getIdAccessory() {
		return idAccessory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_ACCESSORY.ID_ACCESSORY
	 * @param idAccessory  the value for MY_WED_ACCESSORY.ID_ACCESSORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdAccessory(Integer idAccessory) {
		this.idAccessory = idAccessory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_ACCESSORY.ID_WEDDING_HALL
	 * @return  the value of MY_WED_ACCESSORY.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public Integer getIdWeddingHall() {
		return idWeddingHall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_ACCESSORY.ID_WEDDING_HALL
	 * @param idWeddingHall  the value for MY_WED_ACCESSORY.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setIdWeddingHall(Integer idWeddingHall) {
		this.idWeddingHall = idWeddingHall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MY_WED_ACCESSORY.ID_WEDDING_HALL
	 * @return  the value of MY_WED_ACCESSORY.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public String getDsAccessory() {
		return dsAccessory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MY_WED_ACCESSORY.ID_WEDDING_HALL
	 * @param idWeddingHall  the value for MY_WED_ACCESSORY.ID_WEDDING_HALL
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	public void setDsAccessory(String dsAccessory) {
		this.dsAccessory = dsAccessory;
	}
	
}