package com.kinzr.apellian.entity.model;

import java.util.Date;

public class Pkg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idPkg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG.CD_PKG_THEME
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer cdPkgTheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG.NM_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String nmPkg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG.AM_PRICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer amPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG.AM_SALE_PRICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer amSalePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG.CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer cdCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynPublish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Date dtReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG.DS_NOTICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsNotice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG.ID_PKG
     *
     * @return the value of PKG.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdPkg() {
        return idPkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG.ID_PKG
     *
     * @param idPkg the value for PKG.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdPkg(Integer idPkg) {
        this.idPkg = idPkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG.CD_PKG_THEME
     *
     * @return the value of PKG.CD_PKG_THEME
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdPkgTheme() {
        return cdPkgTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG.CD_PKG_THEME
     *
     * @param cdPkgTheme the value for PKG.CD_PKG_THEME
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdPkgTheme(Integer cdPkgTheme) {
        this.cdPkgTheme = cdPkgTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG.NM_PKG
     *
     * @return the value of PKG.NM_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getNmPkg() {
        return nmPkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG.NM_PKG
     *
     * @param nmPkg the value for PKG.NM_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNmPkg(String nmPkg) {
        this.nmPkg = nmPkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG.AM_PRICE
     *
     * @return the value of PKG.AM_PRICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getAmPrice() {
        return amPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG.AM_PRICE
     *
     * @param amPrice the value for PKG.AM_PRICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setAmPrice(Integer amPrice) {
        this.amPrice = amPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG.AM_SALE_PRICE
     *
     * @return the value of PKG.AM_SALE_PRICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getAmSalePrice() {
        return amSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG.AM_SALE_PRICE
     *
     * @param amSalePrice the value for PKG.AM_SALE_PRICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setAmSalePrice(Integer amSalePrice) {
        this.amSalePrice = amSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG.CD_COMPANY
     *
     * @return the value of PKG.CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdCompany() {
        return cdCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG.CD_COMPANY
     *
     * @param cdCompany the value for PKG.CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdCompany(Integer cdCompany) {
        this.cdCompany = cdCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG.YN_PUBLISH
     *
     * @return the value of PKG.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnPublish() {
        return ynPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG.YN_PUBLISH
     *
     * @param ynPublish the value for PKG.YN_PUBLISH
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnPublish(String ynPublish) {
        this.ynPublish = ynPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG.DT_REG
     *
     * @return the value of PKG.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Date getDtReg() {
        return dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG.DT_REG
     *
     * @param dtReg the value for PKG.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDtReg(Date dtReg) {
        this.dtReg = dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG.DS_NOTICE
     *
     * @return the value of PKG.DS_NOTICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsNotice() {
        return dsNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG.DS_NOTICE
     *
     * @param dsNotice the value for PKG.DS_NOTICE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsNotice(String dsNotice) {
        this.dsNotice = dsNotice;
    }
}