package com.kinzr.apellian.entity.model;

import java.util.Date;

public class PkgApplication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.ID_PKG_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Long idPkgApplication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.ID_USER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String idUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idPkg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.CD_BUDGET
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String cdBudget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.YN_ADDTIONAL_01
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynAddtional01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.YN_ADDTIONAL_02
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynAddtional02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.YN_ADDTIONAL_03
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynAddtional03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.YN_ADDTIONAL_04
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynAddtional04;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.YN_ADDTIONAL_05
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynAddtional05;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.YN_ADDTIONAL_06
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynAddtional06;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.YN_ADDTIONAL_07
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynAddtional07;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.YN_ADDTIONAL_08
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynAddtional08;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.YN_ADDTIONAL_09
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynAddtional09;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.YN_ADDTIONAL_10
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String ynAddtional10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Date dtReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.DS_CONSULT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsConsult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_APPLICATION.DS_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsCompany;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.ID_PKG_APPLICATION
     *
     * @return the value of PKG_APPLICATION.ID_PKG_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Long getIdPkgApplication() {
        return idPkgApplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.ID_PKG_APPLICATION
     *
     * @param idPkgApplication the value for PKG_APPLICATION.ID_PKG_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdPkgApplication(Long idPkgApplication) {
        this.idPkgApplication = idPkgApplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.ID_USER
     *
     * @return the value of PKG_APPLICATION.ID_USER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.ID_USER
     *
     * @param idUser the value for PKG_APPLICATION.ID_USER
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.ID_PKG
     *
     * @return the value of PKG_APPLICATION.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdPkg() {
        return idPkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.ID_PKG
     *
     * @param idPkg the value for PKG_APPLICATION.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdPkg(Integer idPkg) {
        this.idPkg = idPkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.CD_BUDGET
     *
     * @return the value of PKG_APPLICATION.CD_BUDGET
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getCdBudget() {
        return cdBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.CD_BUDGET
     *
     * @param cdBudget the value for PKG_APPLICATION.CD_BUDGET
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdBudget(String cdBudget) {
        this.cdBudget = cdBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.YN_ADDTIONAL_01
     *
     * @return the value of PKG_APPLICATION.YN_ADDTIONAL_01
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnAddtional01() {
        return ynAddtional01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.YN_ADDTIONAL_01
     *
     * @param ynAddtional01 the value for PKG_APPLICATION.YN_ADDTIONAL_01
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnAddtional01(String ynAddtional01) {
        this.ynAddtional01 = ynAddtional01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.YN_ADDTIONAL_02
     *
     * @return the value of PKG_APPLICATION.YN_ADDTIONAL_02
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnAddtional02() {
        return ynAddtional02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.YN_ADDTIONAL_02
     *
     * @param ynAddtional02 the value for PKG_APPLICATION.YN_ADDTIONAL_02
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnAddtional02(String ynAddtional02) {
        this.ynAddtional02 = ynAddtional02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.YN_ADDTIONAL_03
     *
     * @return the value of PKG_APPLICATION.YN_ADDTIONAL_03
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnAddtional03() {
        return ynAddtional03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.YN_ADDTIONAL_03
     *
     * @param ynAddtional03 the value for PKG_APPLICATION.YN_ADDTIONAL_03
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnAddtional03(String ynAddtional03) {
        this.ynAddtional03 = ynAddtional03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.YN_ADDTIONAL_04
     *
     * @return the value of PKG_APPLICATION.YN_ADDTIONAL_04
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnAddtional04() {
        return ynAddtional04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.YN_ADDTIONAL_04
     *
     * @param ynAddtional04 the value for PKG_APPLICATION.YN_ADDTIONAL_04
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnAddtional04(String ynAddtional04) {
        this.ynAddtional04 = ynAddtional04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.YN_ADDTIONAL_05
     *
     * @return the value of PKG_APPLICATION.YN_ADDTIONAL_05
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnAddtional05() {
        return ynAddtional05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.YN_ADDTIONAL_05
     *
     * @param ynAddtional05 the value for PKG_APPLICATION.YN_ADDTIONAL_05
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnAddtional05(String ynAddtional05) {
        this.ynAddtional05 = ynAddtional05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.YN_ADDTIONAL_06
     *
     * @return the value of PKG_APPLICATION.YN_ADDTIONAL_06
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnAddtional06() {
        return ynAddtional06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.YN_ADDTIONAL_06
     *
     * @param ynAddtional06 the value for PKG_APPLICATION.YN_ADDTIONAL_06
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnAddtional06(String ynAddtional06) {
        this.ynAddtional06 = ynAddtional06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.YN_ADDTIONAL_07
     *
     * @return the value of PKG_APPLICATION.YN_ADDTIONAL_07
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnAddtional07() {
        return ynAddtional07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.YN_ADDTIONAL_07
     *
     * @param ynAddtional07 the value for PKG_APPLICATION.YN_ADDTIONAL_07
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnAddtional07(String ynAddtional07) {
        this.ynAddtional07 = ynAddtional07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.YN_ADDTIONAL_08
     *
     * @return the value of PKG_APPLICATION.YN_ADDTIONAL_08
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnAddtional08() {
        return ynAddtional08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.YN_ADDTIONAL_08
     *
     * @param ynAddtional08 the value for PKG_APPLICATION.YN_ADDTIONAL_08
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnAddtional08(String ynAddtional08) {
        this.ynAddtional08 = ynAddtional08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.YN_ADDTIONAL_09
     *
     * @return the value of PKG_APPLICATION.YN_ADDTIONAL_09
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnAddtional09() {
        return ynAddtional09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.YN_ADDTIONAL_09
     *
     * @param ynAddtional09 the value for PKG_APPLICATION.YN_ADDTIONAL_09
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnAddtional09(String ynAddtional09) {
        this.ynAddtional09 = ynAddtional09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.YN_ADDTIONAL_10
     *
     * @return the value of PKG_APPLICATION.YN_ADDTIONAL_10
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getYnAddtional10() {
        return ynAddtional10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.YN_ADDTIONAL_10
     *
     * @param ynAddtional10 the value for PKG_APPLICATION.YN_ADDTIONAL_10
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setYnAddtional10(String ynAddtional10) {
        this.ynAddtional10 = ynAddtional10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.DT_REG
     *
     * @return the value of PKG_APPLICATION.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Date getDtReg() {
        return dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.DT_REG
     *
     * @param dtReg the value for PKG_APPLICATION.DT_REG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDtReg(Date dtReg) {
        this.dtReg = dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.DS_CONSULT
     *
     * @return the value of PKG_APPLICATION.DS_CONSULT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsConsult() {
        return dsConsult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.DS_CONSULT
     *
     * @param dsConsult the value for PKG_APPLICATION.DS_CONSULT
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsConsult(String dsConsult) {
        this.dsConsult = dsConsult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_APPLICATION.DS_COMPANY
     *
     * @return the value of PKG_APPLICATION.DS_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsCompany() {
        return dsCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_APPLICATION.DS_COMPANY
     *
     * @param dsCompany the value for PKG_APPLICATION.DS_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsCompany(String dsCompany) {
        this.dsCompany = dsCompany;
    }
}