package com.kinzr.apellian.entity.model;

public class PkgDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_DETAIL.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idPkg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_DETAIL.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer cdCategory;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PKG_DETAIL.CD_THEME
    *
    * @mbg.generated Mon Apr 27 15:07:22 KST 2020
    */
    private Integer cdtheme;
   
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_DETAIL.CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer cdCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_DETAIL.DS_CATEGORY_DETAIL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String dsCategoryDetail;   
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PKG_DETAIL.DS_CATEGORY_DETAIL
    *
    * @mbg.generated Mon Apr 27 15:07:22 KST 2020
    */
   private String nmCategory;
   /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column PKG_DETAIL.DS_CATEGORY_DETAIL
   *
   * @mbg.generated Mon Apr 27 15:07:22 KST 2020
   */
   private String nmCompany;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_DETAIL.ID_PKG
     *
     * @return the value of PKG_DETAIL.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdPkg() {
        return idPkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_DETAIL.ID_PKG
     *
     * @param idPkg the value for PKG_DETAIL.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdPkg(Integer idPkg) {
        this.idPkg = idPkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_DETAIL.CD_CATEGORY
     *
     * @return the value of PKG_DETAIL.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdCategory() {
        return cdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_DETAIL.CD_CATEGORY
     *
     * @param cdCategory the value for PKG_DETAIL.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdCategory(Integer cdCategory) {
        this.cdCategory = cdCategory;
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_DETAIL.CD_CATEGORY
     *
     * @return the value of PKG_DETAIL.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdTheme() {
        return cdtheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_DETAIL.CD_CATEGORY
     *
     * @param cdCategory the value for PKG_DETAIL.CD_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdTheme(Integer cdtheme) {
        this.cdtheme = cdtheme;
    }

        
    
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_DETAIL.CD_COMPANY
     *
     * @return the value of PKG_DETAIL.CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getCdCompany() {
        return cdCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_DETAIL.CD_COMPANY
     *
     * @param cdCompany the value for PKG_DETAIL.CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setCdCompany(Integer cdCompany) {
        this.cdCompany = cdCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_DETAIL.DS_CATEGORY_DETAIL
     *
     * @return the value of PKG_DETAIL.DS_CATEGORY_DETAIL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getDsCategoryDetail() {
        return dsCategoryDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_DETAIL.DS_CATEGORY_DETAIL
     *
     * @param dsCategoryDetail the value for PKG_DETAIL.DS_CATEGORY_DETAIL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setDsCategoryDetail(String dsCategoryDetail) {
        this.dsCategoryDetail = dsCategoryDetail;
    }
    
   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PKG_DETAIL.DS_CATEGORY_DETAIL
    *
    * @return the value of PKG_DETAIL.DS_CATEGORY_DETAIL
    *
    * @mbg.generated Mon Apr 27 15:07:22 KST 2020
    */
   public String getNmCategory() {
       return nmCategory;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PKG_DETAIL.DS_CATEGORY_DETAIL
    *
    * @param dsCategoryDetail the value for PKG_DETAIL.DS_CATEGORY_DETAIL
    *
    * @mbg.generated Mon Apr 27 15:07:22 KST 2020
    */
   public void setNmCategory(String nmCategory) {
       this.nmCategory = nmCategory;
   }
   
   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column PKG_DETAIL.DS_CATEGORY_DETAIL
    *
    * @return the value of PKG_DETAIL.DS_CATEGORY_DETAIL
    *
    * @mbg.generated Mon Apr 27 15:07:22 KST 2020
    */
   public String getNmCompany() {
       return nmCompany;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column PKG_DETAIL.DS_CATEGORY_DETAIL
    *
    * @param dsCategoryDetail the value for PKG_DETAIL.DS_CATEGORY_DETAIL
    *
    * @mbg.generated Mon Apr 27 15:07:22 KST 2020
    */
   public void setNmCompany(String nmCompany) {
       this.nmCompany = nmCompany;
   }
   
   

   
}