package com.kinzr.apellian.entity.model;

public class PkgImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_IMAGES.NO_IMG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Long noImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_IMAGES.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private Integer idPkg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PKG_IMAGES.URL_IMG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    private String urlImg;
    
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column PKG_IMAGES.NM_PKG
    *
    * @mbg.generated Mon Apr 27 15:07:22 KST 2020
    */
   private String nmPkg;
   
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_IMAGES.NO_IMG
     *
     * @return the value of PKG_IMAGES.NO_IMG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Long getNoImg() {
        return noImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_IMAGES.NO_IMG
     *
     * @param noImg the value for PKG_IMAGES.NO_IMG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNoImg(Long noImg) {
        this.noImg = noImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_IMAGES.ID_PKG
     *
     * @return the value of PKG_IMAGES.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public Integer getIdPkg() {
        return idPkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_IMAGES.ID_PKG
     *
     * @param idPkg the value for PKG_IMAGES.ID_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setIdPkg(Integer idPkg) {
        this.idPkg = idPkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_IMAGES.URL_IMG
     *
     * @return the value of PKG_IMAGES.URL_IMG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getUrlImg() {
        return urlImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_IMAGES.URL_IMG
     *
     * @param urlImg the value for PKG_IMAGES.URL_IMG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setUrlImg(String urlImg) {
        this.urlImg = urlImg;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PKG_IMAGES.URL_IMG
     *
     * @return the value of PKG_IMAGES.URL_IMG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public String getNmPkg() {
        return nmPkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PKG_IMAGES.URL_IMG
     *
     * @param urlImg the value for PKG_IMAGES.NM_PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    public void setNmPkg(String nmPkg) {
        this.nmPkg = nmPkg;
    }
    

   
}