package com.kinzr.apellian.entity.model;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.username
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.password
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.NM_USER
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String nmUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.TY_GENDER
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String tyGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.TY_USER
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String tyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.CD_COMPANY
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private Integer cdCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.enabled
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.NO_COUNTRY
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String noCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.NO_TEL
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String noTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.YN_WITHDRAW
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String ynWithdraw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.YN_WITHDRAW_REASON1
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String ynWithdrawReason1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.YN_WITHDRAW_REASON2
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String ynWithdrawReason2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.YN_WITHDRAW_REASON3
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String ynWithdrawReason3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.YN_WITHDRAW_REASON4
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String ynWithdrawReason4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.YN_WITHDRAW_REASON5
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String ynWithdrawReason5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.DT_WITHDRAW
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private Date dtWithdraw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.DT_REG
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private Date dtReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.DS_NOTE
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String dsNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.DS_WITHDRAW
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    private String dsWithdraw;

    
    private String nmUserDelivery1;
    private String noTelDelivery1;
    private String dsAddrDelivery1;

    public String getNmUserDelivery1() {
        return nmUserDelivery1;
    }

    public void setNmUserDelivery1(String nmUserDelivery1) {
        this.nmUserDelivery1 = nmUserDelivery1;
    }

    public String getNoTelDelivery1() {
        return noTelDelivery1;
    }

    public void setNoTelDelivery1(String noTelDelivery1) {
        this.noTelDelivery1 = noTelDelivery1;
    }

    public String getDsAddrDelivery1() {
        return dsAddrDelivery1;
    }

    public void setDsAddrDelivery1(String dsAddrDelivery1) {
        this.dsAddrDelivery1 = dsAddrDelivery1;
    }
    
    ////
    
    private String nmUserDelivery100;
    private String noTelDelivery100;
    private String dsAddrDelivery100;
    
    public String getNmUserDelivery100() {
        return nmUserDelivery100;
    }

    public void setNmUserDelivery100(String nmUserDelivery100) {
        this.nmUserDelivery100 = nmUserDelivery100;
    }

    public String getNoTelDelivery100() {
        return noTelDelivery100;
    }

    public void setNoTelDelivery100(String noTelDelivery100) {
        this.noTelDelivery100 = noTelDelivery100;
    }

    public String getDsAddrDelivery100() {
        return dsAddrDelivery100;
    }

    public void setDsAddrDelivery100(String dsAddrDelivery100) {
        this.dsAddrDelivery100 = dsAddrDelivery100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.username
     *
     * @return the value of USERS.username
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.username
     *
     * @param username the value for USERS.username
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.password
     *
     * @return the value of USERS.password
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.password
     *
     * @param password the value for USERS.password
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.NM_USER
     *
     * @return the value of USERS.NM_USER
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getNmUser() {
        return nmUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.NM_USER
     *
     * @param nmUser the value for USERS.NM_USER
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setNmUser(String nmUser) {
        this.nmUser = nmUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.TY_GENDER
     *
     * @return the value of USERS.TY_GENDER
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getTyGender() {
        return tyGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.TY_GENDER
     *
     * @param tyGender the value for USERS.TY_GENDER
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setTyGender(String tyGender) {
        this.tyGender = tyGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.TY_USER
     *
     * @return the value of USERS.TY_USER
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getTyUser() {
        return tyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.TY_USER
     *
     * @param tyUser the value for USERS.TY_USER
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setTyUser(String tyUser) {
        this.tyUser = tyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.CD_COMPANY
     *
     * @return the value of USERS.CD_COMPANY
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public Integer getCdCompany() {
        return cdCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.CD_COMPANY
     *
     * @param cdCompany the value for USERS.CD_COMPANY
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setCdCompany(Integer cdCompany) {
        this.cdCompany = cdCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.enabled
     *
     * @return the value of USERS.enabled
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.enabled
     *
     * @param enabled the value for USERS.enabled
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.NO_COUNTRY
     *
     * @return the value of USERS.NO_COUNTRY
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getNoCountry() {
        return noCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.NO_COUNTRY
     *
     * @param noCountry the value for USERS.NO_COUNTRY
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setNoCountry(String noCountry) {
        this.noCountry = noCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.NO_TEL
     *
     * @return the value of USERS.NO_TEL
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getNoTel() {
        return noTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.NO_TEL
     *
     * @param noTel the value for USERS.NO_TEL
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setNoTel(String noTel) {
        this.noTel = noTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.YN_WITHDRAW
     *
     * @return the value of USERS.YN_WITHDRAW
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getYnWithdraw() {
        return ynWithdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.YN_WITHDRAW
     *
     * @param ynWithdraw the value for USERS.YN_WITHDRAW
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setYnWithdraw(String ynWithdraw) {
        this.ynWithdraw = ynWithdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.YN_WITHDRAW_REASON1
     *
     * @return the value of USERS.YN_WITHDRAW_REASON1
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getYnWithdrawReason1() {
        return ynWithdrawReason1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.YN_WITHDRAW_REASON1
     *
     * @param ynWithdrawReason1 the value for USERS.YN_WITHDRAW_REASON1
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setYnWithdrawReason1(String ynWithdrawReason1) {
        this.ynWithdrawReason1 = ynWithdrawReason1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.YN_WITHDRAW_REASON2
     *
     * @return the value of USERS.YN_WITHDRAW_REASON2
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getYnWithdrawReason2() {
        return ynWithdrawReason2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.YN_WITHDRAW_REASON2
     *
     * @param ynWithdrawReason2 the value for USERS.YN_WITHDRAW_REASON2
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setYnWithdrawReason2(String ynWithdrawReason2) {
        this.ynWithdrawReason2 = ynWithdrawReason2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.YN_WITHDRAW_REASON3
     *
     * @return the value of USERS.YN_WITHDRAW_REASON3
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getYnWithdrawReason3() {
        return ynWithdrawReason3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.YN_WITHDRAW_REASON3
     *
     * @param ynWithdrawReason3 the value for USERS.YN_WITHDRAW_REASON3
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setYnWithdrawReason3(String ynWithdrawReason3) {
        this.ynWithdrawReason3 = ynWithdrawReason3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.YN_WITHDRAW_REASON4
     *
     * @return the value of USERS.YN_WITHDRAW_REASON4
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getYnWithdrawReason4() {
        return ynWithdrawReason4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.YN_WITHDRAW_REASON4
     *
     * @param ynWithdrawReason4 the value for USERS.YN_WITHDRAW_REASON4
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setYnWithdrawReason4(String ynWithdrawReason4) {
        this.ynWithdrawReason4 = ynWithdrawReason4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.YN_WITHDRAW_REASON5
     *
     * @return the value of USERS.YN_WITHDRAW_REASON5
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getYnWithdrawReason5() {
        return ynWithdrawReason5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.YN_WITHDRAW_REASON5
     *
     * @param ynWithdrawReason5 the value for USERS.YN_WITHDRAW_REASON5
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setYnWithdrawReason5(String ynWithdrawReason5) {
        this.ynWithdrawReason5 = ynWithdrawReason5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.DT_WITHDRAW
     *
     * @return the value of USERS.DT_WITHDRAW
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public Date getDtWithdraw() {
        return dtWithdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.DT_WITHDRAW
     *
     * @param dtWithdraw the value for USERS.DT_WITHDRAW
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setDtWithdraw(Date dtWithdraw) {
        this.dtWithdraw = dtWithdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.DT_REG
     *
     * @return the value of USERS.DT_REG
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public Date getDtReg() {
        return dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.DT_REG
     *
     * @param dtReg the value for USERS.DT_REG
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setDtReg(Date dtReg) {
        this.dtReg = dtReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.DS_NOTE
     *
     * @return the value of USERS.DS_NOTE
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getDsNote() {
        return dsNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.DS_NOTE
     *
     * @param dsNote the value for USERS.DS_NOTE
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setDsNote(String dsNote) {
        this.dsNote = dsNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.DS_WITHDRAW
     *
     * @return the value of USERS.DS_WITHDRAW
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public String getDsWithdraw() {
        return dsWithdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.DS_WITHDRAW
     *
     * @param dsWithdraw the value for USERS.DS_WITHDRAW
     *
     * @mbg.generated Fri May 01 10:41:39 KST 2020
     */
    public void setDsWithdraw(String dsWithdraw) {
        this.dsWithdraw = dsWithdraw;
    }
}