package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.BnfClassBnfImages;
import java.util.List;

public interface BnfClassBnfImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_CLASS_BNF_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(Integer idBnfClassBnfImage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_CLASS_BNF_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(BnfClassBnfImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_CLASS_BNF_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    BnfClassBnfImages selectByPrimaryKey(Integer idBnfClassBnfImage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_CLASS_BNF_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<BnfClassBnfImages> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_CLASS_BNF_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(BnfClassBnfImages record);
    
    // 클래스에 해당하는 깜짝혜택 이미지 리스트
    List<BnfClassBnfImages> selectClassBnfImages(Integer idClass);

}