package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.BnfClassApplication;
import java.util.List;

public interface BnfClassApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_CLASS_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(Integer idClassApplication);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_CLASS_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(BnfClassApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_CLASS_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    BnfClassApplication selectByPrimaryKey(Integer idClassApplication);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_CLASS_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<BnfClassApplication> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_CLASS_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(BnfClassApplication record);
    
    
    // 해당 클래스의 신청한 인원수 가져오기
    int selectByApplyCntByClass(Integer idClassApplication);

    // 해당 유저의 클래스 신청횟수
    int selectByApplyCntByUser(String idUser);

    // 해당 유저의 클래스 신청여부
    int selectApplyRequestByUser(BnfClassApplication bnfApply);
    
    
    
    // 유저 당첨 여부 확인
    BnfClassApplication selectApplyInfo(BnfClassApplication bnfApply);
}