package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.BnfEvent;
import java.util.List;

public interface BnfEventMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	int deleteByPrimaryKey(Integer idBnfEvent);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	int insert(BnfEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	BnfEvent selectByPrimaryKey(Integer idBnfEvent);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	List<BnfEvent> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BNF_EVENT
	 * @mbg.generated  Mon May 18 06:33:12 KST 2020
	 */
	int updateByPrimaryKey(BnfEvent record);
}