package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.BnfClassBnfImages;
import com.kinzr.apellian.entity.model.BnfEventBnfImages;
import java.util.List;

public interface BnfEventBnfImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_EVENT_BNF_IMAGES
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    int deleteByPrimaryKey(Integer idBnfEventBnfImage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_EVENT_BNF_IMAGES
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    int insert(BnfEventBnfImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_EVENT_BNF_IMAGES
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    BnfEventBnfImages selectByPrimaryKey(Integer idBnfEventBnfImage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_EVENT_BNF_IMAGES
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    List<BnfEventBnfImages> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BNF_EVENT_BNF_IMAGES
     *
     * @mbg.generated Mon May 18 06:33:12 KST 2020
     */
    int updateByPrimaryKey(BnfEventBnfImages record);
    
    
    // 이벤트에 해당하는 깜짝혜택 이미지 리스트
    List<BnfEventBnfImages> selectEventBnfImages(Integer idBnfEvent);

}