package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.Board;
import java.util.List;

public interface BoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(Long idBoard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    Board selectByPrimaryKey(Long idBoard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<Board> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOARD
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(Board record);
    
    
    List<Board> selectListType(String type);

}