package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.CdCompany;
import java.util.List;

public interface CdCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(Integer cdCompany);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(CdCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    CdCompany selectByPrimaryKey(Integer cdCompany);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<CdCompany> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(CdCompany record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_COMPANY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<CdCompany> selectLikeCompany(String nmCompany);
    
}