package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.CdMagazineCategory;
import java.util.List;

public interface CdMagazineCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(Integer cdMagazineCategory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(CdMagazineCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    CdMagazineCategory selectByPrimaryKey(Integer cdMagazineCategory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<CdMagazineCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_MAGAZINE_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(CdMagazineCategory record);
}