package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.CdWedCategory;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CdWedCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WED_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(@Param("idWeddingHall") Integer idWeddingHall, @Param("cdCategory") Integer cdCategory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WED_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(CdWedCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WED_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    CdWedCategory selectByPrimaryKey(@Param("idWeddingHall") Integer idWeddingHall, @Param("cdCategory") Integer cdCategory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WED_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<CdWedCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WED_CATEGORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(CdWedCategory record);
}