package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.CdWedAccessory;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CdWedAccessoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WED_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(@Param("idWeddingHall") Integer idWeddingHall, @Param("idAccessory") Integer idAccessory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WED_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(CdWedAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WED_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    CdWedAccessory selectByPrimaryKey(@Param("idWeddingHall") Integer idWeddingHall, @Param("idAccessory") Integer idAccessory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WED_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<CdWedAccessory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WED_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(CdWedAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WED_ACCESSORY
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<CdWedAccessory> selectByWedHall(@Param("idWeddingHall") Integer idWeddingHall, @Param("idAccessory") Integer idAccessory);
}