package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.CdWeddingHall;
import java.util.List;

public interface CdWeddingHallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(Integer idWeddingHall);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(CdWeddingHall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    CdWeddingHall selectByPrimaryKey(Integer idWeddingHall);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<CdWeddingHall> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(CdWeddingHall record);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CD_WEDDING_HALL
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<CdWeddingHall> selectLikeWedHall(String nmWeddingHall);
        
    
    
}