package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.Magazine;
import java.util.List;

public interface MagazineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(Integer idMagazine);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(Magazine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    Magazine selectByPrimaryKey(Integer idMagazine);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<Magazine> selectAll(String category);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(Magazine record);
    
    
    
    
    Magazine selectPreMagazine(Integer idMagazine);
    Magazine selectNextMagazine(Integer idMagazine);

    List<Magazine> selectSearch(String search);
    
    List<Magazine> selectSavedList(String idUser);

    
}