package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.Magazine;
import com.kinzr.apellian.entity.model.MagazineSavedList;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MagazineSavedListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE_SAVED_LIST
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(@Param("idUser") String idUser, @Param("idMagazine") Integer idMagazine);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE_SAVED_LIST
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(MagazineSavedList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE_SAVED_LIST
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    MagazineSavedList selectByPrimaryKey(@Param("idUser") String idUser, @Param("idMagazine") Integer idMagazine);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE_SAVED_LIST
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<MagazineSavedList> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE_SAVED_LIST
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(MagazineSavedList record);
    
}