package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.MagazineCategoryList;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MagazineCategoryListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE_CATEGORY_LIST
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(@Param("idMagazine") Integer idMagazine, @Param("cdMagazineCategory") Integer cdMagazineCategory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE_CATEGORY_LIST
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(MagazineCategoryList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAGAZINE_CATEGORY_LIST
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<MagazineCategoryList> selectAll();
}