package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.MyWed;
import java.util.List;

public interface MyWedMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	int deleteByPrimaryKey(Long idWedding);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	int insert(MyWed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	MyWed selectByPrimaryKey(Long idWedding);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	List<MyWed> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	int updateByPrimaryKey(MyWed record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	MyWed selectByIdUser(String idUser);
	
}