package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.MyWedOption;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyWedOptionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED_OPTION
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	int deleteByPrimaryKey(@Param("idWedding") Long idWedding, @Param("idOption") Integer idOption,
			@Param("idWeddingHall") Integer idWeddingHall);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED_OPTION
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	int insert(MyWedOption record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED_OPTION
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	MyWedOption selectByPrimaryKey(@Param("idWedding") Long idWedding, @Param("idOption") Integer idOption,
			@Param("idWeddingHall") Integer idWeddingHall);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED_OPTION
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	List<MyWedOption> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED_OPTION
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	int updateByPrimaryKey(MyWedOption record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED_OPTION
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	List<MyWedOption> selectByOptnidWedding(@Param("idWedding") Long idWedding);	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED_OPTION
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	MyWedOption selectSumByOptnidWedding(@Param("idWedding") Long idWedding);	
	
	
	
}