package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.MyWedAccessory;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyWedAccessoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED_ACCESSORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	int deleteByPrimaryKey(@Param("idWedding") Long idWedding, @Param("idAccessory") Integer idAccessory,
			@Param("idWeddingHall") Integer idWeddingHall);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED_ACCESSORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	int insert(MyWedAccessory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED_ACCESSORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	List<MyWedAccessory> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MY_WED_ACCESSORY
	 * @mbg.generated  Tue Apr 28 16:45:02 KST 2020
	 */
	List<MyWedAccessory> selectByAsryidWedding(@Param("idWedding") Long idWedding);
	
}