package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.PkgApplication;
import java.util.List;

public interface PkgApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(Long idPkgApplication);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(PkgApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    PkgApplication selectByPrimaryKey(Long idPkgApplication);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<PkgApplication> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_APPLICATION
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(PkgApplication record);
}