package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.PkgImages;
import java.util.List;

public interface PkgImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(Long noImg);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(PkgImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    PkgImages selectByPrimaryKey(Long noImg);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<PkgImages> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(PkgImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<PkgImages> selectByCdpkgTheme(Integer cdPkgTheme);    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG_IMAGES
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<PkgImages> selectByIdpkg(Integer idPkg);    
    
}