package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.Pkg;
import java.util.List;

public interface PkgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int deleteByPrimaryKey(Integer idPkg);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int insert(Pkg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    Pkg selectByPrimaryKey(Integer idPkg);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<Pkg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    int updateByPrimaryKey(Pkg record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKG
     *
     * @mbg.generated Mon Apr 27 15:07:22 KST 2020
     */
    List<Pkg> selectLimit5();    
}