package com.kinzr.apellian.entity.mapper;

import com.kinzr.apellian.entity.model.Users;
import java.util.List;

public interface UsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USERS
	 * @mbg.generated  Mon Apr 27 15:07:22 KST 2020
	 */
	int deleteByPrimaryKey(String username);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USERS
	 * @mbg.generated  Mon Apr 27 15:07:22 KST 2020
	 */
	int insert(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USERS
	 * @mbg.generated  Mon Apr 27 15:07:22 KST 2020
	 */
	Users selectByPrimaryKey(String username);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USERS
	 * @mbg.generated  Mon Apr 27 15:07:22 KST 2020
	 */
	List<Users> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USERS
	 * @mbg.generated  Mon Apr 27 15:07:22 KST 2020
	 */
	int updateByPrimaryKey(Users record);
	int updateGender(Users record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USERS
	 * @mbg.generated  Mon Apr 27 15:07:22 KST 2020
	 */
	int updateByWithdrawKey(Users record);	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USERS
	 * @mbg.generated  Mon Apr 27 15:07:22 KST 2020
	 */
	int updateByPassword(Users record);
	
	int updateDelivery1(Users record);	
	int updateDelivery100(Users record);	
}